# Generated by Django 6.0.2 on 2026-03-18 06:23

from django.db import migrations, models
from django.utils.text import slugify


def _populate_phone_slug(apps, schema_editor):
    Phone = apps.get_model('msdhoni', 'Phone')
    existing = set()

    for phone in Phone.objects.all():
        base = slugify(phone.name)
        slug = base
        index = 1
        while slug in existing or Phone.objects.filter(slug=slug).exclude(pk=phone.pk).exists():
            slug = f"{base}-{index}"
            index += 1
        existing.add(slug)
        phone.slug = slug
        phone.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('msdhoni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('accessory', 'Accessory')], default='mobile', max_length=20),
        ),
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
        migrations.RunPython(
            code=_populate_phone_slug,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(blank=True, unique=True, max_length=120),
        ),
    ]
