# Generated by Django 6.0.2 on 2026-03-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msdhoni', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='discount_percent',
            field=models.IntegerField(default=0, help_text='Discount percentage (0-100%)'),
        ),
    ]
