# Generated by Django 6.0.2 on 2026-03-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msdhoni', '0004_phone_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='deal_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='is_deal',
            field=models.BooleanField(default=False),
        ),
    ]
